services:
  altcha.type:
    class: Huluti\AltchaBundle\Type\AltchaType
    tags: ['form.type']
    arguments:
      $enable: '%huluti_altcha.enable%'
  altcha.validator:
    class: Huluti\AltchaBundle\Validator\AltchaValidator
    tags: ['validator.constraint_validator']
    arguments:
      $enable: '%huluti_altcha.enable%'
      $hmacKey: '%huluti_altcha.hmacKey%'
  Huluti\AltchaBundle\Controller\HulutiAltchaChallengeController:
    public: true
    autowire: true
    autoconfigure: true
    arguments:
      $hmacKey: '%huluti_altcha.hmacKey%'