services:
  altcha.type:
    class: Huluti\AltchaBundle\Type\AltchaType
    tags: ['form.type']
    arguments:
      $enable: '%huluti_altcha.enable%'
      $floating: '%huluti_altcha.floating%'
      $useStimulus: '%huluti_altcha.use_stimulus%'
      $hideLogo: '%huluti_altcha.hide_logo%'
      $hideFooter: '%huluti_altcha.hide_footer%'
      $jsPath: '%huluti_altcha.js_path%'
      $translator: '@translator'
  altcha.validator:
    class: Huluti\AltchaBundle\Validator\AltchaValidator
    tags: ['validator.constraint_validator']
    arguments:
      $enable: '%huluti_altcha.enable%'
      $hmacKey: '%huluti_altcha.hmacKey%'
      $requestStack: '@request_stack'
  Huluti\AltchaBundle\Controller\HulutiAltchaChallengeController:
    public: true
    autowire: true
    autoconfigure: true
    arguments:
      $hmacKey: '%huluti_altcha.hmacKey%'