services:
  altcha.type:
    class: Huluti\AltchaBundle\Type\AltchaType
    tags: ['form.type']
    arguments:
      $enable: '%huluti_altcha.enable%'
      $floating: '%huluti_altcha.floating%'
      $useStimulus: '%huluti_altcha.use_stimulus%'
      $useAssetMapper: '%huluti_altcha.use_asset_mapper%'
      $hideLogo: '%huluti_altcha.hide_logo%'
      $hideFooter: '%huluti_altcha.hide_footer%'
      $jsPath: '%huluti_altcha.js_path%'
      $l18nPath: '%huluti_altcha.l18n_path%'
      $useSentinel: '%huluti_altcha.use_sentinel%'
      $challengeUrl: '%huluti_altcha.sentinel.challenge_url%'
  altcha.validator:
    class: Huluti\AltchaBundle\Validator\AltchaValidator
    tags: ['validator.constraint_validator']
    arguments:
      $enable: '%huluti_altcha.enable%'
      $hmacKey: '%huluti_altcha.hmacKey%'
      $requestStack: '@request_stack'
  Huluti\AltchaBundle\Controller\HulutiAltchaChallengeController:
    public: true
    autowire: true
    autoconfigure: true
    arguments:
      $challengeOptionResolver: '@Huluti\AltchaBundle\Service\ChallengeResolverInterface'
  Huluti\AltchaBundle\Service\ChallengeResolverInterface:
    class: Huluti\AltchaBundle\Service\ChallengeResolver
    arguments:
      $hmacKey: '%huluti_altcha.hmacKey%'
      $expires: '+15 minute'